水果:
  pingguo: 苹果
  xiangjiao: 香蕉
  xigua: 西瓜
  tiangua: 甜瓜
  pear: 梨
  ganzhe: 甘蔗
  tao: 蜜桃
  youtao: 油桃
  ganju: 蜜桔
  shatangju: 沙糖桔
  penggan: 椪柑
  qicheng: 脐橙
  shanzha: 山楂
  putao: 葡萄
  boluo: 菠萝
  caomei: 草莓
  longyan: 龙眼
  xingzi: 杏子
  lizi: 李子
  hetao: 核桃
  banli: 板栗
  kuihua: 葵花
  hamigua: 哈密瓜
  shizi: 柿子
  lizhi: 荔枝
  youzi: 柚子
  zao: 枣
  mangguo: 芒果
  yingtao: 樱桃
  pipa: 枇杷
  huolongguo: 火龙果
  shiliu: 石榴
  mihoutao: 猕猴桃
  shengnvguo: 圣女果
  yangmei: 杨梅
